### PR TITLE
Fixing tcltk issue

### PR DESCRIPTION
**Pull request by jhollway**
# Description

Fixes issue #1 by making `tcltk` optional.

Not yet a complete fix, but opening the pull request to get things started...

* Added pull request template for future PRs

# How Has This Been Tested?

* Builds locally.
* NB: I have not tested it without `tcltk` yet.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jhollway** [comment]
@TomSnijders I've switched this pull request to the main branch now. Please review these changes and we can discuss what else is required for the fix.

**Comment by TomSnijders** [comment]
The validity of this solution should be checked by appropriate checks including R 4.0.2. no Windows and on Mac.

**Review by TomSnijders — CHANGES_REQUESTED** [review]
I just made some changes.

**Comment by TomSnijders** [comment]
The results are that we still have three errors.
Windows: I thought I had give configure.ac LF line endings, but there still is the warning message about this, which does not appear on checks on my own machine.
Mac: error: X11 is missing; I thought that was checked in the code.
Ubuntu: "no DISPLAY variable so Tk is not available": this should also be checked.

**Comment by jhollway** [comment]
Three errors:

- [ ] Windows: configure.ac line endings
- [ ] Mac: X11/XQuartz missing
- [ ] Ubuntu: potential issues with subdirectory size, current time verification, and "Siena.txt" file

- **

Not sure about the Windows issue, as the file is also with LF line endings on my local copy, with no changes to commit in git.

**Comment by TomSnijders** [comment]
It seems that in spite of the warnings, compilation does succeed for Windows as well as Mac. 
Windows warning: line endings of configure.ac;
Mac warning: Can't exec "aclocal".

**Review by TomSnijders — APPROVED** [review]

**Comment by TomSnijders** [comment]
tcltk now is an optional package, i.e., moved from "Imports" to "Suggests". All checks passed for version 1.2-26.

**Pull request merged**
