### PR TITLE
Update installation instructions in readme

### PR DESCRIPTION
**Pull request by vankesteren**
# Description
I changed the installation section of the readme to be more user-friendly. It is now also higher-up in the readme than before

- Also removed "about" heading
- Added "Data types" heading

# Checklist:

## Checks

- [x] If possible, I have added tests that prove my fix is effective or that my feature works
- [x] The package builds on my OS without issues NB: I tested on our linux server and the linux binary build yields the following problem, unrelated to the current change. I guess that would be fixed by installing the system dependency.
image
- [x] My changes generate no new warnings

## Documentation

- [x] I have commented my code inline, particularly in hard-to-understand areas
- [x] If function added/modified, I have added/modified documentation (in .R file)
- [x] If effect added/modified, I have added/modified section 12 of the manual
- [ ] I have added a description of all changes to this pull request above and to the NEWS.md file
- [ ] I have bumped the version in the DESCRIPTION and man/RSiena-package.md files by the appropriate increment:
  - 'major' (incompatible API changes)
  - 'minor' (add functionality in a backwards compatible manner)
  - 'patch' (backwards compatible bug fixes)

### CODE REVIEW

**Comment by vankesteren** [comment]
NB: the PR template is a little intense for PRs at this level. I'm happy to hear your feedback on my changes!

**Review by J535D165 — APPROVED** [review]
Nice update.

**Review by csteglich — APPROVED** [review]
Useful changes; this also helps positioning the develop branch as a natural first place to try out new software functionality.

**Comment by csteglich** [comment]
Concerning the PR template heaviness, well, yes, this apparently relates to more serious code change - but it was instructive for me to see this how the workflow is structured. Thank you, both!

**Comment by vankesteren** [comment]
Hi @csteglich, why did you close this PR without merging?

**Comment by csteglich** [comment]
I don't know, to be honest - probably I considered the compilation checks after @J535D165 's PR sufficient for both his and your PRs together, but I see that they do not cumulate and need to be handled separately. Thanks for pointing me back here. Briefly re-opened this one for merging, should be okay now.

**Pull request merged**
